services:
  - type: web
    name: crypto-tracker
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
        libsdl2-dev \
        libsdl2-image-dev \
        libsdl2-mixer-dev \
        libsdl2-ttf-dev
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python app.py
